version: "3"

services:
  server:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ZULIP_URL=
      - BOT_EMAIL=
      - BOT_TOKEN=
      - REDIS_CONNSTRING=redis://redis
  redis:
    image: "redis:alpine"
    restart: always
